In [ ]:
#numpy is a scientific package
#you can use for mathematical applications
#this is a library making special arrays, can resemble matrices and run faster than
#the normal lists

In [ ]:
#array is a grid containing the values inside it
#lists are basically slow and elements are comma sepereted.
'''
1d array , 2d and 3d array can be make
there is shape and axis. 
list consumed more memory but the array contains less memory and
convineint for higher mathematics

'''

In [ ]:

# how to install
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [9]:
#how to import

import numpy as np

In [11]:
# make a numpy array

x = np.array([1,2,3,4])
print(x , type(x))

y=[1,2,3,4]
print(y,type(y))

[1 2 3 4] <class 'numpy.ndarray'>
[1, 2, 3, 4] <class 'list'>


In [12]:
#image manipulations in ML uses numpy
#array has less methods for modification
#list has more methods for modification

#time of creation

%timeit x = np.array([1,2,3,4,5])

2.36 μs ± 212 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
%timeit x = [1,2,3,4,5]

242 ns ± 29.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
#making of the array and multidimension arrays
import numpy as np

x = [1,2,3,4]

y = np.array(x)
print(y,type(y))

[1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
# a program to make an empty list , take input and make an array out of it

l=[]
for i in range (1,5):
    int_1 = int(input("Enter the value"))
    l.append(int_1)
#gave input :10,20,30,40
print(np.array(l))

[10 20 30 40]


In [18]:
# i d has []
# 2 d has [[]]
# 3 d has [[[]]]

# to make the array and check its dimension

print("The dimensions of y is :",y.ndim)

The dimensions of y is : 1


In [ ]:
#making a 2d array , #but keep in mind that all rows and columns must have the same
# data inside it.

ar2 = np.array([
    [1,0,0],[0,1,0],[0,0,1]
])

print(ar2)
print("The dimensions of ar2 is :",ar2.ndim)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
The dimensions of ar2 is : 2


In [21]:
'''make a 3d array like this'''

ar3 = np.array([[
    [1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]
    ]])
print(ar3)
print("The dimensions of ar3 is :",ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
The dimensions of ar3 is : 3


In [22]:
# make n dimension
arn = np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)


[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [23]:
# making a function to make the np array 
# using some special functions

#,fill 0 , fill 1 , make the empty array, make with range, make a digonal array
# and linearly spaced array

#making the array with zeroes

import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [25]:
# make the 2d zero array
ar_zeroes1 = np.zeros((3,3))
print(ar_zeroes1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
