In [ ]:
# Indexing in Arrays and their slicing

'''
indexing is from 0 to n-1
and also from -1 to 0

indexing is from row wise is 0 to n
and indexing is from 0 to 1 column wise

and the -1 to 0 applies to them as well
'''

In [14]:
import numpy as np

var = np.array([9,8,7,6])

print(var.shape)

for idx in range(0,3):
    print(var[idx], end =" ")


print()

for idx in range(-1,-5,-1):
    print(var[idx], end =" ")



(4,)
9 8 7 
6 7 8 9 

In [ ]:
# make a 2 d array

var1= np.array([
    [9,8,7],
    [4,5,6]
])

print(var1.ndim)

# want to access 8
print(var1[0][1])

#1st think about the row then think about the column

2
8


In [21]:
# make a 3 d array

var1= np.array([
    [
    [1,0,0],
    [0,1,0],
    [0,0,1],
],

   [
    [2,0,0],
    [0,2,0],
    [0,0,2],
]
])

print(var1.ndim)
print()


print(var1)

#  want to access the middle most 2

print(var1[1][1][1]) # 2nd row,then second row then second columnn

3

[[[1 0 0]
  [0 1 0]
  [0 0 1]]

 [[2 0 0]
  [0 2 0]
  [0 0 2]]]
2


In [27]:
#slicing inside the array

var1 = np.array([1,2,3,4,5])

# indexes are from 0 to 4

# start : stop :step  are the parameters to do the slicing
#print from 2 t0 4
print(var1[1:4:1])
print()

#from the start to 4
print(var1[0:3])
print()

# from 2 to end
print(var1[1:])
print()

#print the entire
print(var1[::])
print()

#print the sequence 1 3 5
print(var1[::2])  #1st blank means from the start begin
# second blank means the complete list
# 2 is the step value , Since by default is 1



[2 3 4]

[1 2 3]

[2 3 4 5]

[1 2 3 4 5]

[1 3 5]


In [30]:
# make a 2 d array

var1= np.array(
    [
    [1,0,0],
    [0,1,0],
    [0,0,1],
] 
)

# print all but dont print the last one in a sequence

# flatten and exclude last element
print(var1.flatten()[:-1])

[1 0 0 0 1 0 0 0]


In [36]:
# make a 2 d array

var1= np.array(
    [
    [1,2,3,4,5],
    [9,8,7,6,5],
    [11,12,13,14,15],
] 
)

# print 8 to 5

print(var1[1,1:5])


[8 7 6 5]
