In [1]:
#making the array using the random number array

# rand function makes the number between 0 or 1
#  how to apply it

import numpy as np

var = np.random.rand(4) #gives you the random numbers from 0 to 1 between

print(var)

[0.86710799 0.4640501  0.42333796 0.73393686]


In [ ]:
#above used the +ve numbers only

var = np.random.randn(4)
print(var)  #gives you the -ve values as well

[ 1.12346189  1.1684171   0.68314692 -0.57987243]


In [3]:
#make use of thr ranf : includes the 0 also

var = np.random.ranf(4)
print(var)

[0.59855106 0.90035213 0.4243121  0.73970442]


In [5]:
# use of the rand int function , will generate the numbers in a given range
# from the minimum and the maximum value

# var  = np.random.randint(min=10,max=20,total=5)
var  = np.random.randint(10,20,5)
print(var)

[14 10 15 14 15]


In [6]:
# Data types in numpy array

# many data types stored in a variable
# a numpy array can store many number and string combinations
# it is known as the data type


# bool tru and False
# int , int c , int p , uint unsigned , float ,complex _
# complex 64,128

var = np.array([1,2,3,4])
print("dtype : ",var.dtype)

dtype :  int64


In [7]:
var = np.array([1,2,2.5,3,4])
print("dtype : ",var.dtype)

dtype :  float64


In [9]:
var = np.array(['A','S','D','F'])
print(var.dtype)

<U1


In [10]:
# conversion of the data types

x = np.array([1,2,3,4])

print("Data Type :",x.dtype)

Data Type : int64


In [11]:
# convert the above into int 8
x = np.array([1,2,3,4],dtype = np.int8)
print("Dtype :",x.dtype)

Dtype : int8


In [15]:
# above is in the int type , it need to be converted into float
x1= np.array([1,2,3,4],dtype="f")
print("Dtype :",x1.dtype)

#the other way

new = np.float32(x1)
print("new dtype is",new.dtype)
#by this you will prevent the changing of the original array

# convert back to int

new = np.int_(new)
print(" again new dtype is",new.dtype)

Dtype : float32
new dtype is float32
 again new dtype is int64


In [16]:
# use of the astype
x3=np.array([1,2,3,4])
new_1 = x3.astype(float)
print(new_1,new_1.dtype)



[1. 2. 3. 4.] float64
