In [3]:
# Copy and view
import numpy as np
var1 = np.array([1,2,3,4])

copy_var = var1.copy()

print(copy_var)

[1 2 3 4]


In [ ]:
'''
main differences 

copy : will own the data.
 the copy of  an array is always a new array.
 the changes made inside the copy will not affect the original array.

 view: the view will not own the data.
 changes will apply on both the view and the original data.

 always go on with the copy.
 
'''

In [6]:
# join two arrays or split two arrays.

#must understand that the shape must be the same.

import numpy as np

var = np.array([1,2,3,4])
new_var = np.array([9,8,7,6])

ar = np.concatenate((var,new_var)) #use the parenthesis here
print(ar)

[1 2 3 4 9 8 7 6]


In [12]:
# for the 2 dimensions there is two axis 0 for the column and 1 for the row

# make 2 dimesnsion array

i1 = np.eye(3)
i2 = i1*3

print(i1)
print()
print(i2)
print()
# concatenate
ar = np.concatenate((i1,i2),axis=1) #horizontal merge
print(ar)
print()
ar = np.concatenate((i1,i2),axis=0) #vertical merge
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]

[[1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


In [17]:
# stack and merge


# for the 2 dimensions there is two axis 0 for the column and 1 for the row

# make 2 dimesnsion array

i1 = np.eye(3)
i2 = i1*3

# print(i1)
# print()
# print(i2)
# print()

ar = np.stack((i1,i2))
print(ar)
ar = np.hstack((i1,i2))
print(ar)
ar = np.dstack((i1,i2))
print(ar)
print()


[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[3. 0. 0.]
  [0. 3. 0.]
  [0. 0. 3.]]]
[[1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]]
[[[1. 3.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [1. 3.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [1. 3.]]]



In [22]:
# splitting an array

# 1d array

import numpy as np

var = np.array([1,2,3,4,5,6])

print(var)

ar = np.array_split(var,6) #2nd parameters is for the number of arrays to make
print(ar)

[1 2 3 4 5 6]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [ ]:
#make a 2 dimensional array

i3 = np.eye(3)
print(i3)

# now split its rows wise
print(np.array_split(i3,3,axis=0)) # 1 array per row, row means axis 1
# 3 means result gave 3 rows
#axis 0 means along the column

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[array([[1., 0., 0.]]), array([[0., 1., 0.]]), array([[0., 0., 1.]])]
