In [2]:
import numpy as np

ht = np.array([165,166,167,169,170,172])
print("sqrt of ht is = ",np.round(np.sqrt(ht),3)) #make it 3 decimal places

sqrt of ht is =  [12.845 12.884 12.923 13.    13.038 13.115]


In [4]:
var = np.array([45])
print("sin of 45 = ",np.sin(var))
print("cos of 45 = ",np.cos(var))

sin of 45 =  [0.85090352]
cos of 45 =  [0.52532199]


In [ ]:
# cumulative sum
var = np.array([1,2,3])
print(np.cumsum(var)) #keep 1 , then for 2 do (1+2)=3 [place at index of 2] now for 3 do (3+3)=6 (final index)

[1 3 6]


In [13]:
#operation on the matrices require them to be of the same shape.
#But sometimes, we can face that they are of different shapes.
#Still we got a way out for this.

#we will get the value error 
#using broadcasting numpy array

V1 = np.array([[1,2,3]])
print("V1 :",V1)

V2 = np.array([
    [1],
    [2],
    [3]
])
print("V2 :")
print(V2)

print()
print(V1.shape)
print(V2.shape)

print()
print(np.multiply(V1,V2))


V1 : [[1 2 3]]
V2 :
[[1]
 [2]
 [3]]

(1, 3)
(3, 1)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [ ]:
'''
time to understand the broadcasting.
there are 2 matrices , 1st one (2x1)
and the other one :            (2x3)
now compare them 2 and 2 are same so keep 2 in mind
now compare them 1 and 3, max(1,3) = 3 
the final matrix will result to  (2x3) ... that's the array broadcasting
'''