In [2]:
#making an array full of ones
import numpy as np
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [ ]:
#making an empty array

ar_em = np.empty(4)
print(ar_em) #it wll take the memory of the recently created array

[1. 1. 1. 1.]


In [ ]:
ar_rn = np.arange(4)
print(ar_rn) #made the array with the range

[0 1 2 3]


In [ ]:
#making the identity matrix like array
# all digonals are filled with one
ar_dig = np.eye(3) #made a 3 by 3 identity matrix
print(ar_dig)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# make the identity matrix using the dimension 3,5
ar_demo = np.eye(3,5)
print(ar_demo)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [11]:
'''make the special type area using the linspace function'''

ar_lin = np.linspace(0,20,num=5)
# do 1+11 = 12 / 5 = 2.5 app. now 1 is starting : 1 +2.5 = 3.5 then
# 3.5 + 2.5 = 6 and so on to make the even spacing among numbers of the interval 1 to 11
# and understand that both are inclusive
print(ar_lin)

[ 0.  5. 10. 15. 20.]
