In [4]:
# inserting the data in the arrays
import numpy as np
var = np.array([1,2,3,4])
print(var,var.dtype,type(var))

# np.insert(name of array, index, what value)


v= np.insert(var,2,40)
print(v)

[1 2 3 4] int64 <class 'numpy.ndarray'>
[ 1  2 40  3  4]


In [5]:
# the value 60 needs to be added to the index 2 and 4

v1 = np.insert(var,(2,4),60)
print(v1)

[ 1  2 60  3  4 60]


In [ ]:
# this will work with the int values only and not the float values

var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert(var1, 2 ,4, axis =0) #along the row but add at each column
print(v1)
var1 = np.array([[1,2,3],[1,2,3]]) #along the column but add in each row
v2 = np.insert(var1, 2 ,4, axis =1)
print(v2)

[[1 2 3]
 [1 2 3]
 [4 4 4]]
[[1 2 4 3]
 [1 2 4 3]]


In [9]:
# insert the row 10 10 10 in the final row
var1 = np.array([[1,2,3],[1,2,3]])
v1 = np.insert(var1, 2 ,[10,10,10], axis =0) #along the row but add at each column
print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [10 10 10]]


In [11]:
# use of the append functions inside the 

var = np.array([1,2,3,4,5])

#append the value 6.5 in the end

x = np.append(var,6.5)
print(x)

[1.  2.  3.  4.  5.  6.5]


In [21]:
# append this 0 0 1 in the v1
v1 = np.eye(3,3)
print(v1)
print("\n\n")
v1 = np.append(v1,[0,0,1])
print(v1.reshape(4,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [ ]:
#making a matrix inside the numpy.
# this is going to work when multiplication of the matrices

# main difference inside the array and matrix is that
# all elements of an array will multiply to all the other elements of the other array.
# but when the matrix is multiplied , its done according to its rules

var  = np.matrix([[1,2,3],[2,3,4]])
print(var,type(var))  

# this is made the same way but its done in a different way.

[[1 2 3]
 [2 3 4]] <class 'numpy.matrix'>


In [ ]:
# The use of the multiplication and the dot product

A = np.matrix([[1,2],[1,2]])
B = np.matrix([[1,2],[1,2]])

print(A*B)
print()
print(A.dot(B))

print()
print(np.multiply(A,B)) #inconsistent results

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]

[[1 4]
 [1 4]]


In [ ]:
The functions that are applicable to the matrices
using numpy are : 
transpose, swap axes, inverse, power, determinate



In [35]:
A = np.matrix([
    [1,2,3],
    [4,5,6]
])

print(np.transpose(A))

print("\nShortcut")
print(A.T)

[[1 4]
 [2 5]
 [3 6]]

Shortcut
[[1 4]
 [2 5]
 [3 6]]


In [47]:
# Swap axes
print(np.swapaxes(A,0,1))


[[1 4]
 [2 5]
 [3 6]]


In [49]:
# inverse of a matrix
A = np.matrix([
    [1,2],
    [3,4]
])

var3 = np.linalg.inv(A)
print(var3)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [59]:
# Adjoint  of a matrix
A = np.array([
    [1, 2],
    [3, 4]
])

det = np.linalg.det(A) # find the determinant [ensure a square matrix]
inv = np.linalg.inv(A)

adj = det * inv
print(adj)

[[ 4. -2.]
 [-3.  1.]]


In [60]:
# power find the cube.
print(A)
pwr = int(input("enter the power"))

A2 = np.linalg.matrix_power(A,2)
print(A2)

[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]
