In [1]:
#Some other main functions inside Numpy

import numpy as np

# The use of the Shuffle functions

var = np.array([1,2,3,4,5])

np.random.shuffle(var)

print(var)

[3 1 2 4 5]


In [4]:
#to get the unique data from the array

var1 = np.array([1,1,1,1,5,5,5,5,5])

x= np.unique(var1)

print(x)

x= np.unique(var1,return_index=True) #make the returning the index

print(x) 

x= np.unique(var1,return_index=True,return_counts=True) #make the returning the index and counts

print(x) 

[1 5]
(array([1, 5]), array([0, 4]))
(array([1, 5]), array([0, 4]), array([4, 5]))


In [ ]:
# resize the var1 stored inside the above one

y = np.resize(var1,(3,3)) #since 9 elements make a 3x3 matrix

print(y)  #most utility inside the machine learning

[[1 1 1]
 [1 5 5]
 [5 5 5]]


In [ ]:
#Time to flatted and Ravel the arrays

Order : CFAK

By default is C row major form
For F is Fortran style ordering in the column major
A means to flatten in a column major if there is Fortran manner store of data
K means to flatten the elements if there is a C style store of data

In [7]:
# flatten y
print(y.flatten()) #normal way
print()

print(y.flatten(order="C"))
print()

print(y.flatten(order="F"))
print()

print(y.flatten(order="A"))
print()

print(y.flatten(order="K"))
print()

[1 1 1 1 5 5 5 5 5]

[1 1 1 1 5 5 5 5 5]

[1 1 5 1 5 5 1 5 5]

[1 1 1 1 5 5 5 5 5]

[1 1 1 1 5 5 5 5 5]



In [ ]:
# ravel the array

print(np.ravel(y))
print(np.ravel(y,order="C"))
print(np.ravel(y,order="F"))
print(np.ravel(y,order="A"))
print(np.ravel(y,order="K"))

#use the flatten since its a copy,
# ravel returns a view of the flattened data into many ordered formats.
# Since a view , then any modifications will alter the original data.

[1 1 1 1 5 5 5 5 5]
[1 1 1 1 5 5 5 5 5]
[1 1 5 1 5 5 1 5 5]
[1 1 1 1 5 5 5 5 5]
[1 1 1 1 5 5 5 5 5]
