In [1]:
import numpy as np

var = np.array([1,2,3,4,5])

for i in var:
    print(i,end=" ... ")

1 ... 2 ... 3 ... 4 ... 5 ... 

In [ ]:
#iteration inside the 2 d array

var1 = np.array([
    [1,2,3,4],
    [1,2,3,4]
    
    ])

#one way
for i in var1:
    print(i)

print()

#the other way

#this will make the entire array into a single line form
for i in var1:
    for j in i:
        print(j,end=" . ")

[1 2 3 4]
[1 2 3 4]

1 . 2 . 3 . 4 . 1 . 2 . 3 . 4 . 

In [14]:
#iteration inside the 3 d array

var1 = np.array([
    [
    [1,2,34],
    [1,2,34],
    [1,2,34]
    ]
    ,
    [
    [1,2,35],
    [1,2,35],
    [1,2,35]
    ]
])

#one way
for i in var1:
    print(i)

print()

#the other way

#this will make the entire array into a single line form
for i in var1:
    for j in i:
        for k in j:
            print(k, end="_ _")

#this is other way
print()
for i in np.nditer(var1):
    print(i,end=" ")

[[ 1  2 34]
 [ 1  2 34]
 [ 1  2 34]]
[[ 1  2 35]
 [ 1  2 35]
 [ 1  2 35]]

1_ _2_ _34_ _1_ _2_ _34_ _1_ _2_ _34_ _1_ _2_ _35_ _1_ _2_ _35_ _1_ _2_ _35_ _
1 2 34 1 2 34 1 2 34 1 2 35 1 2 35 1 2 35 

In [18]:
#utility :
# we want that the indexing is also shown

# get the data point with the indexes as well

var1 = np.array(
    [
    [1,2,35],
    [1,2,35],
    [1,2,35]
    ]
)

for i,d in np.ndenumerate(var1):
    print(i,d, end="\n")

(0, 0) 1
(0, 1) 2
(0, 2) 35
(1, 0) 1
(1, 1) 2
(1, 2) 35
(2, 0) 1
(2, 1) 2
(2, 2) 35
