In [ ]:
#Shapes in Numpy 

import numpy as np

var = np.array(
    [[1,2],[2,3]]
)

print(var)
print()
print(var.shape) #tuple of row and column(row,col)

[[1 2]
 [2 3]]

(2, 2)


In [4]:
var1 = np.array([1,2,3,4],ndmin=4)
print(var1,var1.ndim,var1.shape)

[[[[1 2 3 4]]]] 4 (1, 1, 1, 4)


In [10]:
#reshaping the arrays in numpy

var2 = np.array([1,2,3,4,5,6])
# var2.reshape(rows = 3, columns = 2) this is a template
print(var2.reshape(3,2) )
print(var2)
print(var2.ndim)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
1


In [12]:
# make a 3x3 matrix from 1 dim.
# reshape it to 3x3 
# then reshape it back to 1 dimesion

i3 = np.array([1,0,0,0,1,0,0,0,1])

temp = i3.reshape(3,3)

print(temp,temp.shape)

i3 = temp.reshape(-1)

print(i3,i3.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[1 0 0 0 1 0 0 0 1] (9,)
