In [2]:
#Arithemetic operations on the Arrays of Numpy

import numpy as np

var1 = np.array([1,2,3,4])
print(var1)

# do the  additions with 3

var2 = var1+3
print(var)

print("result of addition :",var1+var2)
print("result of subtraction :",var1-var2)
print("result of multiplication :",var1*var2)
print("result of division :",var1/var2)



[1 2 3 4]
[4 5 6 7]
result of addition : [ 5  7  9 11]
result of subtraction : [-3 -3 -3 -3]
result of multiplication : [ 4 10 18 28]
result of division : [0.25       0.4        0.5        0.57142857]


In [3]:
#using np.add()

print(np.add(var1,var2))

[ 5  7  9 11]


In [ ]:
# do the additions of 2 , 2d arrays

A = np.eye(2,2)
B = np.eye(2,2)
  # always need to keep in mind that the dimensions must always coincide
print(np.add(A,B))

[[2. 0.]
 [0. 2.]]


In [6]:
# make the reciprocal of A

print(np.reciprocal(A))

[[ 1. inf]
 [inf  1.]]


C:\Users\Dell\AppData\Local\Temp\ipykernel_3780\3299362028.py:3: RuntimeWarning: divide by zero encountered in reciprocal
  print(np.reciprocal(A))


In [8]:
# other functions

# make a 1d array
var1 = np.array([1,5,5,5,20])

print("min :",np.min(var1))
print("max :",np.max(var1))



min : 1
max : 20


In [9]:
#get the positions

print("min pos :",np.argmin(var1))
print("max pos :",np.argmax(var1))

min pos : 0
max pos : 4


In [12]:
#now important work, using this with the 2 dimensionals

var1 = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
    ]
)


print("min :",np.min(var1))
print("max :",np.max(var1))

print("min pos :",np.argmin(var1))
print("max pos :",np.argmax(var1))

#role of the axis
# two axis : 0 and 1 , o:column and 1 :row
print("according to column")
print("min pos :",np.argmin(var1,axis=0))
print("max pos :",np.argmax(var1,axis=0))

print("according to row")
print("min pos :",np.argmin(var1,axis=1))
print("max pos :",np.argmax(var1,axis=1))

min : 1
max : 16
min pos : 0
max pos : 15
according to column
min pos : [0 0 0 0]
max pos : [3 3 3 3]
according to row
min pos : [0 0 0 0]
max pos : [3 3 3 3]


In [ ]:
'''
this means :

according to column
min pos : [0 0 0 0]
max pos : [3 3 3 3]

at each column, 0 index, the min values exist
at each column, 3 index, the max values exist

according to row
min pos : [0 0 0 0]
max pos : [3 3 3 3]
at each row, 0 index, the min values exist
at each row, 3 index, the max values exist


'''